# Copyright (C) 2009 the authors.
#
# This file is part of the Fhtagn! C++ Library, and may be distributed under
# the following license terms and conditions as set forth in the COPYING file
# included in this source distribution.
Import('env')
import os.path

SOURCES = [
]

HEADERS = [
  'ntree.h',
  os.path.join('detail', 'ntree.tcc'),
]

env.addSources('fhtagn', SOURCES)
env.addHeaders('fhtagn', HEADERS)
