# Copyright (C) 2008 the authors.
#
# This file is part of the Fhtagn! C++ Library, and may be distributed under
# the following license terms and conditions as set forth in the COPYING file
# included in this source distribution.
Import('env')

SOURCES = [
  'tasklet.cpp',
]

HEADERS = [
  'tasklet.h',
]

env.addSources('fhtagn', SOURCES)
env.addHeaders('fhtagn', HEADERS)
env.addLibs('fhtagn', [('boost', 'thread'), ('boost', 'signals')])
