# Copyright (C) 2008 the authors.
#
# This file is part of the Fhtagn! C++ Library, and may be distributed under
# the following license terms and conditions as set forth in the COPYING file
# included in this source distribution.
Import('env')

if env.has_key('FHTAGN_CPPUNIT_VERSION'):
  TESTSUITE_SOURCES = [
    'pointers_test.cpp',
    'enhanced_types_test.cpp',
    'transcoding_test.cpp',
    'allocator_test.cpp',
    'misc_test.cpp',
    'meta_test.cpp',
    'testdriver.cpp',
  ]

  if env.has_key('FHTAGN_BOOST_VERSION'):
    TESTSUITE_SOURCES += [
      'variant_test.cpp',
      'threads_test.cpp',
    ]

  env.addSources('testsuite', TESTSUITE_SOURCES)
  env.addLibs('testsuite', ['fhtagn', 'fhtagn_util', 'cppunit'])
  if env.has_key('FHTAGN_BOOST_VERSION'):
    env.addLibs('testsuite', [('boost', 'signals'), ('boost', 'thread')])

  if env.get('GCOV', False):
    env.addLibs('testsuite', ['gcov'])

if env.has_key('FHTAGN_BOOST_VERSION'):
  ALLOCSPEED_SOURCES = [
    'allocspeed.cpp',
  ]

  env.addSources('allocspeed', ALLOCSPEED_SOURCES)
  env.addLibs('allocspeed', ['fhtagn', 'fhtagn_util', ('boost', 'thread'),
      ('boost', 'program_options')])

  if env.get('GCOV', False):
    env.addLibs('allocspeed', ['gcov'])
