# Copyright (C) 2009 the authors.
#
# This file is part of the Fhtagn! C++ Library, and may be distributed under
# the following license terms and conditions as set forth in the COPYING file
# included in this source distribution.
Import('env')
import os.path

SOURCES = [
]

HEADERS = [
  'allocator.h',
  'defaults.h',
  'utility.h',
  'memory_pool.h',
  'fixed_pool.h',
  'pool_allocator.h',
  os.path.join('detail', 'allocator.tcc'),
  os.path.join('detail', 'defaults.tcc'),
  os.path.join('detail', 'memory_pool.tcc'),
  os.path.join('detail', 'fixed_pool.tcc'),
  os.path.join('detail', 'pool_allocator.tcc'),
]

env.addSources('fhtagn', SOURCES)
env.addHeaders('fhtagn', HEADERS)
