# Copyright (C) 2008 the authors.
#
# This file is part of the Fhtagn! C++ Library, and may be distributed under
# the following license terms and conditions as set forth in the COPYING file
# included in this source distribution.
Import('env')

import os.path

SOURCES = []

HEADERS = []

if env.has_key('FHTAGN_CPPUNIT_VERSION'):
  SOURCES += [
    'cppunit_output.cpp',
  ]

  HEADERS += [
    'cppunit_output.h',
  ]


HEADERS += [
  'stopwatch.h',
]
if env.has_key('HAVE_GETRUSAGE') and env.has_key('HAVE_GETTIMEOFDAY'):
  SOURCES += [
    os.path.join('platform', 'unix', 'stopwatch.cpp'),
  ]
elif not env.is_unix():
  SOURCES += [
    os.path.join('platform', 'win32', 'stopwatch.cpp'),
  ]

env.addSources('fhtagn_util', SOURCES)
env.addHeaders('fhtagn_util', HEADERS)
