/**
 * $Id$
 *
 * Copyright (C) 2009 the authors.
 *
 * Author: Jens Finkhaeuser <unwesen@users.sourceforge.net>
 *
 * This file is part of the Fhtagn! C++ Library, and may be distributed under
 * the following license terms:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 **/

#ifndef FHTAGN_SHARED_PTR_H
#define FHTAGN_SHARED_PTR_H

/**
 * Defines the following classes, either from the TR1 namespace (if available),
 * or from boost (if availble).
 *
 * It makes sense to use Fhtagn's definitions (if you're using Fhtagn! anyway),
 * as they'll use defintions from the std namespace as they become available.
 **/


// Prefer the TR1 definition
#if defined(HAVE_TR1_MEMORY)

#include <tr1/memory>
namespace fhtagn {
using std::tr1::shared_ptr;
using std::tr1::weak_ptr;
using std::tr1::enable_shared_from_this;

using std::tr1::static_pointer_cast;
using std::tr1::dynamic_pointer_cast;
using std::tr1::const_pointer_cast;

} // namespace fhtagn

#else // HAVE_TR1_MEMORY

// Only if tr1::shared_ptr is not available, use boost::shared_ptr
#if defined(HAVE_BOOST_SHARED_PTR_HPP)

#include <boost/shared_ptr.hpp>
#include <boost/pointer_cast.hpp>
#include <boost/enable_shared_from_this.hpp>

namespace fhtagn {
using boost::shared_ptr;
using boost::weak_ptr;
using boost::enable_shared_from_this;

using boost::static_pointer_cast;
using boost::dynamic_pointer_cast;
using boost::const_pointer_cast;

} // namespace fhtagn

#else // HAVE_BOOST_SHARED_PTR_HPP

// Can't really build this, error out.
#error Neither tr1::shared_ptr nor boost::shared_ptr available.

#endif // HAVE_BOOST_SHARED_PTR_HPP

#endif // HAVE_TR1_MEMORY

#endif // guard
