/**
 * $Id$
 *
 * This file is part of the Fhtagn! C++ Library.
 * Copyright (C) 2009 Jens Finkhaeuser <unwesen@users.sourceforge.net>.
 *
 * Author: Henning Pfeiffer <slashgod@users.sourceforge.net>
 * Author: Jens Finkhaeuser <unwesen@users.sourceforge.net>
 *
 * This program is licensed as free software for personal, educational or
 * other non-commerical uses: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Alternatively, licenses for commercial purposes are available as well.
 * Please send your enquiries to the copyright holder's address above.
 **/

#include <fhtagn/fhtagn-config.h>
#include <fhtagn/version.h>

#define FHTAGN_STRINGIFY(n) FHTAGN_STRINGIFY_HELPER(n)
#define FHTAGN_STRINGIFY_HELPER(n) #n

/**
 * For (temporary) compatibility with autotools build
 **/
#if defined(PACKAGE_MAJOR)
#define FHTAGN_MAJOR PACKAGE_MAJOR
#endif

#if defined(PACKAGE_MINOR)
#define FHTAGN_MINOR PACKAGE_MINOR
#endif

#if defined(PACKAGE_MAJOR) && defined(PACKAGE_MINOR)
#define FHTAGN_VERSION PACKAGE_MAJOR.PACKAGE_MINOR
#endif

/**
 * end of autotools compatibility
 **/

namespace fhtagn {


std::pair<boost::uint16_t, boost::uint16_t>
version()
{
    return std::make_pair<boost::uint16_t, boost::uint16_t>(FHTAGN_MAJOR, FHTAGN_MINOR);
}



char const * const copyright_string = "Fhtagn! " FHTAGN_STRINGIFY(FHTAGN_VERSION)
    " - Copyright (c) 2007,2008,2009 by the authors.\n"
    "This version of Fhtagn! is released under the Boost Software License\n"
    "Version 1.0 from August 17th, 2003.";


char const * const license_string =
    "Boost Software License - Version 1.0 - August 17th, 2003\n"
    "\n"
    "Permission is hereby granted, free of charge, to any person or organization\n"
    "obtaining a copy of the software and accompanying documentation covered by\n"
    "this license (the \"Software\") to use, reproduce, display, distribute,\n"
    "execute, and transmit the Software, and to prepare derivative works of the\n"
    "Software, and to permit third-parties to whom the Software is furnished to\n"
    "do so, all subject to the following:\n"
    "\n"
    "The copyright notices in the Software and this entire statement, including\n"
    "the above license grant, this restriction and the following disclaimer,\n"
    "must be included in all copies of the Software, in whole or in part, and\n"
    "all derivative works of the Software, unless such copies or derivative\n"
    "works are solely in the form of machine-executable object code generated by\n"
    "a source language processor.\n"
    "\n"
    "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
    "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
    "FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT\n"
    "SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE\n"
    "FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,\n"
    "ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER\n"
    "DEALINGS IN THE SOFTWARE.";

} // namespace fhtagn
